// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type lbrLbrData struct {
	_       structs.HostLayout
	PidTgid uint64
	NrBytes int64
	Rip     uint64
	Rsp     uint64
	Rbp     uint64
	Entries [32]struct {
		_    structs.HostLayout
		From uint64
		To   uint64
		_    [8]byte
	}
}

// loadLbr returns the embedded CollectionSpec for lbr.
func loadLbr() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LbrBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lbr: %w", err)
	}

	return spec, err
}

// loadLbrObjects loads lbr and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lbrObjects
//	*lbrPrograms
//	*lbrMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLbrObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLbr()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lbrSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbrSpecs struct {
	lbrProgramSpecs
	lbrMapSpecs
	lbrVariableSpecs
}

// lbrProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbrProgramSpecs struct {
	CaptureLbr *ebpf.ProgramSpec `ebpf:"capture_lbr"`
}

// lbrMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbrMapSpecs struct {
	CommMap *ebpf.MapSpec `ebpf:"comm_map"`
	LbrMap  *ebpf.MapSpec `ebpf:"lbr_map"`
}

// lbrVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbrVariableSpecs struct {
	CPU_MASK   *ebpf.VariableSpec `ebpf:"CPU_MASK"`
	TARGET_PID *ebpf.VariableSpec `ebpf:"TARGET_PID"`
	LbrBuff    *ebpf.VariableSpec `ebpf:"lbr_buff"`
}

// lbrObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLbrObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbrObjects struct {
	lbrPrograms
	lbrMaps
	lbrVariables
}

func (o *lbrObjects) Close() error {
	return _LbrClose(
		&o.lbrPrograms,
		&o.lbrMaps,
	)
}

// lbrMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLbrObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbrMaps struct {
	CommMap *ebpf.Map `ebpf:"comm_map"`
	LbrMap  *ebpf.Map `ebpf:"lbr_map"`
}

func (m *lbrMaps) Close() error {
	return _LbrClose(
		m.CommMap,
		m.LbrMap,
	)
}

// lbrVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLbrObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbrVariables struct {
	CPU_MASK   *ebpf.Variable `ebpf:"CPU_MASK"`
	TARGET_PID *ebpf.Variable `ebpf:"TARGET_PID"`
	LbrBuff    *ebpf.Variable `ebpf:"lbr_buff"`
}

// lbrPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLbrObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbrPrograms struct {
	CaptureLbr *ebpf.Program `ebpf:"capture_lbr"`
}

func (p *lbrPrograms) Close() error {
	return _LbrClose(
		p.CaptureLbr,
	)
}

func _LbrClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lbr_x86_bpfel.o
var _LbrBytes []byte
