// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadUprobe returns the embedded CollectionSpec for uprobe.
func loadUprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load uprobe: %w", err)
	}

	return spec, err
}

// loadUprobeObjects loads uprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*uprobeObjects
//	*uprobePrograms
//	*uprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadUprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadUprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// uprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type uprobeSpecs struct {
	uprobeProgramSpecs
	uprobeMapSpecs
	uprobeVariableSpecs
}

// uprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type uprobeProgramSpecs struct {
	CaptureUprobe *ebpf.ProgramSpec `ebpf:"capture_uprobe"`
}

// uprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type uprobeMapSpecs struct {
	UprobeRegsRb *ebpf.MapSpec `ebpf:"uprobe_regs_rb"`
}

// uprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type uprobeVariableSpecs struct {
	UPROBE_TARGET_PID *ebpf.VariableSpec `ebpf:"UPROBE_TARGET_PID"`
}

// uprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type uprobeObjects struct {
	uprobePrograms
	uprobeMaps
	uprobeVariables
}

func (o *uprobeObjects) Close() error {
	return _UprobeClose(
		&o.uprobePrograms,
		&o.uprobeMaps,
	)
}

// uprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type uprobeMaps struct {
	UprobeRegsRb *ebpf.Map `ebpf:"uprobe_regs_rb"`
}

func (m *uprobeMaps) Close() error {
	return _UprobeClose(
		m.UprobeRegsRb,
	)
}

// uprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type uprobeVariables struct {
	UPROBE_TARGET_PID *ebpf.Variable `ebpf:"UPROBE_TARGET_PID"`
}

// uprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type uprobePrograms struct {
	CaptureUprobe *ebpf.Program `ebpf:"capture_uprobe"`
}

func (p *uprobePrograms) Close() error {
	return _UprobeClose(
		p.CaptureUprobe,
	)
}

func _UprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed uprobe_x86_bpfel.o
var _UprobeBytes []byte
